controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gripper_controller:
      type: velocity_controllers/JointGroupVelocityController

# Gripper
gripper_controller:
  ros__parameters:
    joints:
    - Spin_Arm_Joint
    - Arm_Joint
    - Spin_Hammer_Joint
    - Hammer_Joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity